backend:
  name: github
  branch: main
  repo: brolgadigital/brolgadigital
  base_url: https://brolgadigital-cms.herokuapp.com/
  commit_messages:
    create: 'Created {{collection}} “{{slug}}”'
    update: 'Updated {{collection}} “{{slug}}”'
    delete: 'Deleted {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Uploaded “{{path}}”'
    deleteMedia: '[skip ci] Deleted “{{path}}”'

media_folder: static/images/uploads
public_folder: /assets

site_url: https://brolgadigital.com.au
display_url: https://brolgadigital.com.au

collections:
  - name: blog
    identifier_field: name
    label: Blog
    folder: content/blog
    create: true
    slug: '{{fields.path}}'
    preview_path: 'blog/{{fields.path}}'
    path: 'blog/{{fields.path}}'
    fields:
      - { name: layout, label: Layout, widget: hidden, default: 'blog' }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { name: thumbnail, label: Featured Image, widget: image, required: false }
  - name: portfolio
    identifier_field: name
    label: Portfolio
    folder: content/portfolio
    create: true
    slug: '{{fields.path}}'
    preview_path: 'portfolio/{{fields.path}}'
    path: 'portfolio/{{fields.path}}'
    fields:
      - { name: layout, label: Layout, widget: hidden, default: 'portfolio' }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: string }
      - { name: thumbnail, label: Featured Image, widget: image, required: false }
      - { name: website, label: Project Website, widget: string, required: false }
      - { name: body, label: Body, widget: markdown }
       