backend:
  name: github
  branch: main
  repo: brolgadigital/brolgadigital
  base_url: https://brolgadigital-cms.herokuapp.com/
  commit_messages:
    create: 'Created {{collection}} “{{slug}}”'
    update: 'Updated {{collection}} “{{slug}}”'
    delete: 'Deleted {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Uploaded “{{path}}”'
    deleteMedia: '[skip ci] Deleted “{{path}}”'

media_folder: static/images/uploads
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: layout, label: Layout, widget: hidden, default: blog }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { name: thumbnail, label: Featured Image, widget: image, required: false }
  - name: portfolio
    label: Portfolio
    folder: content/portfolio
    create: true
    fields:
      - { name: path, label: Path }
      - { name: layout, label: Layout, widget: hidden, default: blog }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { name: thumbnail, label: Featured Image, widget: image } 