backend:
  name: github
  branch: main
  repo: brolgadigital/brolgadigital
  base_url: https://brolgadigital-cms.herokuapp.com/
  commit_messages:
    create: 'Created {{collection}} “{{slug}}”'
    update: 'Updated {{collection}} “{{slug}}”'
    delete: 'Deleted {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Uploaded “{{path}}”'
    deleteMedia: '[skip ci] Deleted “{{path}}”'

media_folder: 'static/images' # repo location
public_folder: '/assets' # gatsby location

site_url: https://brolgadigital.com.au
display_url: https://brolgadigital.com.au

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: '{{fields.path}}'
    path: '{{slug}}/index'
    fields:
      - { name: layout, label: Layout, widget: hidden, default: 'blog' }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { name: thumbnail, label: Featured Image, widget: image, required: false }

  - name: portfolio
    label: Portfolio
    folder: content/portfolio
    create: true
    slug: '{{fields.path}}'
    path: '{{slug}}/index'
    fields:
      - { name: layout, label: Layout, widget: hidden, default: 'portfolio' }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: subtitle, label: Subtitle, widget: string }
      - { name: description, label: Description, widget: text }
      - { name: summary, label: Summary, widget: text }
      - { name: thumbnail, label: Featured Image, widget: image, required: false }
      - { name: quote, label: Quote, widget: text }
      - { name: quoteAttribute, label: Quote Attribute, widget: string }
      - { name: website, label: Project Website, widget: string, required: false }
      - { name: body, label: Body, widget: markdown }
       